SearchArea:
  frontLength: 600
  leftLength: 300
  rightLength: 300

SearchPoints:
  - id: 0
    uavPosF: 200
    uavPosL: 0
    uavPosU: 20
    uavYaw: 0
    yawRange: 120
    timeout: 300
  - id: 1
    uavPosF: 200
    uavPosL: 0
    uavPosU: 20
    uavYaw: 90
    yawRange: 120
    timeout: 300

uavInitialPos: [[0], [0], [10]]

targetInitialPos: [[-156], [218], [0]]

podInitialData:
  pitchDeg: 30
  yawDeg: 0
  hfovDeg: 40
  maxRateDeg: 20

preSearchData:
  - pitchDeg: 30
    yawDeg: -50
    hfovDeg: 40
    maxRateDeg: 5
  - pitchDeg: 30
    yawDeg: 50
    hfovDeg: 40
    maxRateDeg: 5

dockData:
  pitchDeg: 20
  yawDeg: 0
  hfovDeg: 50
  maxRateDeg: 10

searchConfig:
  - hfovPitchRatio: 3
    theTime: 2
    widthRatio: 0.06

targetSimilarityThreshold: 0.2

onReportFaliure: 'next' # 'next' or 'remove'

usvGuideSideLength: 500

others:
  - 'usv'
  - 'tuav1'
  - 'tuav2'
  - 'tuav3'
  - 'tuav6'
  - 'streamer'

related:
  - 'usv'
  - 'streamer'