SearchArea:
  frontLength: 2000
  leftLength: 1700
  rightLength: 1500

SearchPoints:
  - id: 0
    uavPosF: 300
    uavPosL: 0
    uavPosU: 40
    uavYaw: 90
    yawRange: 120
    timeout: 300
  - id: 1
    uavPosF: 300
    uavPosL: 0
    uavPosU: 40
    uavYaw: 210
    yawRange: 120
    timeout: 300
  - id: 2
    uavPosF: 300
    uavPosL: 0
    uavPosU: 40
    uavYaw: 330
    yawRange: 120
    timeout: 300

uavInitialPos: [[0], [0], [10]]

targetInitialPos: [[-156], [218], [0]]

podInitialData:
  pitchDeg: 0
  yawDeg: 0
  hfovDeg: 40
  maxRateDeg: 20

dockData:
  pitchDeg: 20
  yawDeg: -20
  hfovDeg: 50
  maxRateDeg: 10

searchConfig:
  - hfovPitchRatio: 3
    theTime: 6
    widthRatio: 0.06
  - hfovPitchRatio: 3
    theTime: 10
    widthRatio: 0.06
  - hfovPitchRatio: 3
    theTime: 15
    widthRatio: 0.06
