SearchArea:
  frontLength: 2000
  leftLength: 1700
  rightLength: 1500

SearchPoints:
  - id: 0
    uavPosF: 950
    uavPosL: 0
    uavPosU: 20
    uavYaw: 90
    yawRange: 130
    timeout: 300
  - id: 1
    uavPosF: 950
    uavPosL: 0
    uavPosU: 20
    uavYaw: 210
    yawRange: 130
    timeout: 300
  - id: 2
    uavPosF: 950
    uavPosL: 0
    uavPosU: 20
    uavYaw: 330
    yawRange: 130
    timeout: 300

uavInitialPos: [[0], [0], [10]]

targetInitialPos: [[-156], [218], [0]]

podInitialData:
  pitchDeg: 30
  yawDeg: 0
  hfovDeg: 40
  maxRateDeg: 20

preSearchData:
  - pitchDeg: 20
    yawDeg: -50
    hfovDeg: 40
    maxRateDeg: 5
  - pitchDeg: 20
    yawDeg: 50
    hfovDeg: 40
    maxRateDeg: 5

dockData:
  pitchDeg: 2
  yawDeg: 4
  hfovDeg: 5
  maxRateDeg: 10

searchConfig:
  - hfovPitchRatio: 3
    theTime: 3
    widthRatio: 0.06
  - hfovPitchRatio: 3
    theTime: 5
    widthRatio: 0.1

targetSimilarityThreshold: 0.2

onReportFaliure: 'next' # 'next' or 'remove'

usvGuideSideLength: 500

others:
  - 'usv'
  - 'tuav1'
  - 'tuav2'
  - 'tuav3'
  - 'tuav6'
  - 'streamer'

related:
  - 'usv'
  - 'streamer'

laserOn: True

guideWidth:
  min: 0.15
  max: 0.25
  avg: 0.2

guideMaxRateDeg: 2

trackWidth:
  min: 0.15
  max: 0.25
  avg: 0.2

trackMaxRateDeg: 2