SearchArea:
  frontLength: 1300
  leftLength: 300
  rightLength: 0

SearchPoints:
  - id: 0
    uavPosF: -500
    uavPosL: 0
    uavPosU: 7.5
    uavYaw: 0
    yawRange: 140
    timeout: 300

uavInitialPos: [[0], [0], [7.5]]

targetInitialPos: [[-700], [700], [0]]

podInitialData:
  pitchDeg: -5
  yawDeg: 60
  hfovDeg: 40
  maxRateDeg: 20

preGuideData:
  - pitchDeg: 4
    yawDeg: -20
    hfovDeg: 20
    maxRateDeg: 5
  - pitchDeg: 4
    yawDeg: 20
    hfovDeg: 20
    maxRateDeg: 5

dockData:
  pitchDeg: 4
  yawDeg: 0
  hfovDeg: 20
  maxRateDeg: 20

searchConfig:
  - theTime: 4
    widthRatio: 0.1

targetSimilarityThreshold: 0.2

onReportFailure: 'next' # 'next' or 'remove'

usvGuideSideLength: 500

others:
  - 'arm'
  - 'usv'
  - 'tuav2'
  - 'tuav3'
  - 'tuav6'

related:
  - 'usv'

laserOn: True

guideWidth:
  min: 0.08
  max: 0.12
  avg: 0.1

guideMaxRateDeg: 2

trackWidth:
  min: 0.10
  max: 0.50

trackMaxRateDeg: 20

uavYawDeg: 120

myDatalinkIpAddr: '192.168.147.30'
usvDatalinkIpAddr: '192.168.147.60'

oneShot: True
