SearchPoints:
  - uavPosF: 300
    uavPosL: 0
    uavPosU: 40
    uavYaw: -90
    timeout: 10
  - uavPosF: 300
    uavPosL: 0
    uavPosU: 40
    uavYaw: 90
    timeout: 10

uavInitialPos: [[0], [0], [10]]

targetInitialPos: [[-156], [218], [0]]

dockData:
  pitchDeg: 20
  yawDeg: -20
  hfovDeg: 50
  maxRateDeg: 10